docs/en/example/publiccode.minimal.yml, docs/en/example/publiccode.yml, docs/en/schema.rst, docs/it/example/publiccode.minimal.yml, docs/it/example/publiccode.yml, docs/it/schema.rst, pull_request_template.md
Inserting BCP47 language tag
Substituting the ISO 639 lang tag for its superset, BCP47. The related issue is #2 .
=> Inserting BCP47 language tag

CHANGELOG.md, README.it.md, README.md, docs/en/example/publiccode.minimal.yml, docs/en/example/publiccode.yml, docs/en/index.rst, docs/en/schema.core.rst, docs/en/schema.it.rst, docs/it/example/publiccode.minimal.yml, docs/it/example/publiccode.yml, docs/it/index.rst, docs/it/schema.core.rst, docs/it/schema.it.rst
This PR ports the Italian extensions to 0.2.
Relevant commits:
* feat: mods to the italian schema
* fix: removed designKit section
* add: changelog info
* add: English translation of the schema.it
* fix: maintainance -> maintenance
* ported examples to new version of schema
* port examples to core-0.2
=> Release core-0.2/it-0.2

docs/en/country.rst, docs/en/example/publiccode.minimal.yml, docs/en/example/publiccode.yml, docs/en/schema.core.rst, docs/en/schema.it.rst, docs/it/country.rst, docs/it/example/publiccode.minimal.yml, docs/it/example/publiccode.yml, docs/it/schema.core.rst, docs/it/schema.it.rst
This PR switches the boolean key values to `true/false` from `yes/no` for compatibility with the latest YAML standard https://yaml.org/spec/1.2/spec.html#id2803629. 
This fixes #8. 
@alranel should we draft a new release? Something like `core-0.3` or `core-0.2.1`?
=> Switch boolean to true/false from yes/no

CHANGELOG.rst, docs/en/example/publiccode.yml, docs/en/schema.core.rst, docs/it/example/publiccode.yml, docs/it/schema.core.rst
This PR mandates to insert the phone number as a string. As such, it mandates to explicitly insert double quotes around the phone number.
=> Mandate double quotes around phone numbers

docs/en/schema.core.rst
Fixed a few typos
One important (output -> input) some uncountables and then some minor punctuation and whitespace.
=> Fixed a few typos

docs/fr/schema.core.rst
A contribution to help to translate the documentation in French, started here :  https://github.com/italia/publiccode.yml/pull/73. I'm focusing on schema.core.rst. 
As it is, the document is partially translated.
=> Fr translation

CHANGELOG.rst, docs/en/schema.core.rst, docs/it/schema.core.rst
Fixes #76.
Should this warrant a bump to the standard's version? I bet all `publiccode.yml` files out there are already UTF-8 encoded.
=> Explicitly state UTF-8 is the only valid encoding.

docs/fr/categories-list.rst, docs/fr/conf.py, docs/fr/country.rst, docs/fr/example.rst, docs/fr/example/publiccode.minimal.yml, docs/fr/example/publiccode.yml, docs/fr/forks.rst, docs/fr/index.rst, docs/fr/schema.core.rst, docs/fr/schema.it.rst, docs/fr/scope-list.rst
I decided to start the french translation of your documentation. PublicCode project is something really interesting and I thought it deserved a french translation.
I hope that it will help you to kickstart the french documentation.
It still miss some files and I hope to have time to complete them ! 
Be aware that forks.rst is partially translated.
=> Initialize French translation

Example.de.rst, Readme.de.md, categories-list.de.rst, country.de.rst, docs/de/schema.de.rst, forks.de.rst, index.de.rst, schema.core.de.rst, scope-list.de.rst
German translation of documentation and minor fixes of German extension
We translated the documentation into German. We also did some minor fixes on the German extension.
=> German translation of documentation and minor fixes of German extension

docs/standard/schema.core.rst
Remove the limit in the Standard to allow each presentation level (ie. websites / catalogs / search engines) decide if and how to truncate them.
Fix #58.
=> docs(standard): remove the characters limit for features

docs/standard/example/publiccode.yml, docs/standard/schema.core.rst
As discussed in https://github.com/publiccodeyml/publiccode.yml/discussions/122#discussioncomment-1835681
> @bfabio
> I've always felt that {input,output}Types were influenced by [Desktop files](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)
>
> In general, that's a pretty desktop-centric key that is not really all that relevant besides for softwareType: standalone/desktop,  and even for those applications brings a little value and is deemed not worth to keep updated. That's a guaranteed for  incomplete information.
>
> Case in point: not a single publiccode.yml in the Italian software catalog uses it.
>
> IMO we should just deprecate it.
=> docs(standard): deprecate inputTypes and outputTypes

docs/standard/example/publiccode.minimal.yml, docs/standard/example/publiccode.yml, docs/standard/schema.core.rst
genericName doesn't really fit software outside Desktop environments
and is often misused in practice. Also, we don't offer any controlled vocabulary
for generic names.
The 'shortDescription' and 'name' keys are good enough.
Fix #59.
=> docs(standard): make genericName optional and deprecate it

docs/standard/example/publiccode.yml, docs/standard/schema.core.rst
monochromeLogo is rarely used and rarely useful and the monochrome version
can always be obtained from main logo.
Fix #66.
=> docs(standard): deprecate monochromeLogo

docs/standard/country.rst, docs/standard/example/publiccode.minimal.yml, docs/standard/example/publiccode.yml, docs/standard/schema.core.rst, docs/standard/schema.it.rst
As discussed in https://github.com/publiccodeyml/publiccode.yml/discussions/115
@remcohaszing wrote:
> This specification defines a YAML file which should use yes/no is accepted in several places. However, the meaning of yes/no is ambiguous in YAML. In YAML 1.1 and older [these values represent booleans](https://yaml.org/type/bool.html), but in YAML 1.2 [they don’t](https://yaml.org/spec/1.2.0/#id2602744), meaning they represent strings.
>
> I suggest to remove this ambiguity by changing them to unambigous booleans (true/false) in the specification.
=> docs(standard): specify YAML 1.2 as the file format

docs/it/categories-list.rst, docs/standard/categories-list.rst
Proposal to add educational-content category
This new category would fit better for GCompris.
Added the new category to categories-list.rst in en and it.
=> proposal to add educational-content category

docs/de/schema.core.rst, docs/fr/schema.core.rst, docs/it/schema.core.rst, docs/standard/schema.core.rst
As stated in the following [thread](https://github.com/publiccodeyml/publiccode.yml/discussions/114#discussioncomment-1787018). It would be logical to make the `releaseDate` key optional.
Main reasons that can be coined for this are: 
- Some repositories don't use release tags (SemVer). These repo's don't have a logical release date. In practice a lot of repositories will use Continuous Delivery and for these this will be the case.
- It could be argued that it is undesirable if the publiccode.yml becomes a file that has to be updated very often. In the case of developer.overheid.nl we can also fetch the date of the last release via the Gitlab/Github API.
=> Make "releaseDate" key an optional key

docs/de/schema.core.rst, docs/fr/schema.core.rst, docs/it/schema.core.rst, docs/standard/schema.core.rst
The key description in `softwareType` had a wrong key, the right one is correctly listed in the Allowed values as `addon`.
=> fix: wrong key in `softwareType` description

docs/fr/schema.it.rst, docs/standard/schema.it.rst
The key was always supposed to be `modelloInteroperabilita` and the example had the correct spelling.
The tooling always checked for the right spelling, though.
=> fix: embarrassing and long-standing typo in Italian section

docs/standard/index.rst
The German registry of open source for public administration also uses publiccode.yml, see https://wikijs.opencode.de/de/Hilfestellungen_und_Richtlinien/Leitlinien
=> Mention opencode.de

governance/charter.md, governance/procedure-proposing-changes-and-voting.md
=> docs: don't use GitHub teams links because they are not public

docs/de/schema.core.rst, docs/standard/schema.core.rst
Anticipating https://github.com/publiccodeyml/publiccode.yml/pull/198, I switched the American English spelling of `organizations` into `organisations` :)
=> Switch spelling: "organizations" into "organisations" 
